### ISSUE TITLE
Set config.yml via enviroment

### ISSUE THREAD

**Issue by bralbral** [tacyuuhon/clickhouse-chproxy#26]
Good day! I would like to use image ch-proxy in docker stack deploy. Tell me, is it possible to set config.yml settings through enviroment in docker-compose.yml? 

```

snippet of config.yml
server:
  http:
      listen_addr: ":9090"
      allowed_networks: ["127.0.0.0/24"]
```

For example, it is like :

```
snippet of docker-compose.yml
...
enviroment:
  - "SERVER__HTTP__LISTEN_ADDR=:9090"
...
```
